_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.10.0
        t:
            "1":
                - 1
                - 11
                - 49
                - 51
                - 55
                - 71
                - 98
                - 105
            "2":
                - 1
                - 11
                - 49
                - 51
                - 55
                - 71
                - 98
                - 105
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.0
            "5": 0.19.1
            "6": 4.38.2
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
eval_data_path:
    value: ../tinyagent_dataset/testing_data.json
eval_steps:
    value: 1000
gradient_accumulation_steps:
    value: 4
learning_rate:
    value: 0.0001
model_name:
    value: squeeze-ai-lab/TinyAgent-1.1B
num_train_epochs:
    value: 1
num_virtual_tokens:
    value: 3000
output_dir_base:
    value: /home/ksoh99/SPD_tinyagent/prefixtuning/prefix_tuning_output
per_device_train_batch_size:
    value: 1
save_steps:
    value: 1000
tokenizer_name:
    value: TinyLlama/TinyLlama-1.1B-Chat-v1.0
train_data_path:
    value: ../tinyagent_dataset/training_data.json
wandb_project:
    value: tinyagent-prefix-tuning
wandb_run_name:
    value: tinyagent_vt3000_lr1e-04_ep1_20241219_202035
warmup_steps:
    value: 100
